name: Build
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-frontend:
    runs-on: unpmtu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache npm
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install all dependencies
        run: npm i

      - name: Run build
        run: npm run build
        working-directory: ./frontend
